<%@ page contentType="text/html;charset=UTF-8" language="java" %>
jumpToSystemInfo()
{
    window.location.href="/superAdmin/systemInfo";
},
jumpToBasicInfoAdmin()
{
    window.location.href="/superAdmin/basicInfoAdmin";
},
jumpToInnAdmin()
{
    window.location.href="/superAdmin/innAdmin";
},
jumpToOuttAdmin()
{
    window.location.href="/superAdmin/outtAdmin";
},
jumpToStockAdmin()
{
    window.location.href="/superAdmin/stockAdmin";
},
jumpToReportAdmin()
{
    window.location.href="/superAdmin/reportAdmin";
},
jumpToCrmAdmin()
{
    window.location.href="/superAdmin/crmAdmin";
},
logout()
{
    window.localStorage.clear()
    this.$message.success('退出成功')
    window.location.href="/";
},