<%@ page contentType="text/html;charset=UTF-8" language="java" %>
jumpToSystemInfo()
{
window.location.href="/admin/systemInfo";
},
jumpToBasicInfoAdmin()
{
window.location.href="/admin/basicInfoAdmin";
},
jumpToInnAdmin()
{
window.location.href="/admin/innAdmin";
},
jumpToOuttAdmin()
{
window.location.href="/admin/outtAdmin";
},
jumpToStockAdmin()
{
window.location.href="/admin/stockAdmin";
},
jumpToReportAdmin()
{
window.location.href="/admin/reportAdmin";
},
jumpToCrmAdmin()
{
window.location.href="/admin/crmAdmin";
},
logout()
{
window.localStorage.clear()
this.$message.success('退出成功')
window.location.href="/";
},