<%@ page contentType="text/html;charset=UTF-8" language="java" %>
jumpToStaffAdmin()
{
    window.location.href="/staffAdmin";
},
jumpToTypeAdmin()
{
window.location.href="/typeAdmin";
},
jumpToGoodsAdmin()
{
    window.location.href="/goodsAdmin";
},
jumpToInAdmin()
{
    window.location.href="/inAdmin";
},
jumpToOutAdmin()
{
    window.location.href="/outAdmin";
},
jumpToInventoryAdmin()
{
    window.location.href="/inventoryAdmin";
},
jumpToCrmAdmin()
{
window.location.href="/crmAdmin";
},